repos:
  - repo: local
    hooks:
      - id: ruff-linter
        name: Ruff Linter
        entry: poetry run ruff check --fix --cache-dir .ruff_cache_local
        language: system
        types: [python]
        require_serial: true
      
      - id: ruff-formatter
        name: Ruff Formatter
        entry: poetry run ruff format --cache-dir .ruff_cache_local
        language: system
        types: [python]
      
      - id: mypy
        name: MyPy
        entry: poetry run mypy app/
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
